sonar.projectKey=taller-sast-jairo
sonar.projectName=taller-sast-jairo
sonar.sourceEncoding=UTF-8

sonar.sources=apps

sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.spec.ts,**/*.test.ts,**/*.e2e-spec.ts,**/*.min.js
